### PR TITLE
Fix broken link

### PR DESCRIPTION
**Pull request by robbyhorvath**
Issue: https://github.com/logdna/terraform-provider-logdna/issues/55

### CODE REVIEW

**Comment by mdeltito** [comment]
@logdnabot test this

**Comment by seeruyy** [comment]
@logdnabot test this

**Comment by seeruyy** [comment]
@logdnabot test this

**Comment by seeruyy** [comment]
@logdnabot test this

**Comment by seeruyy** [comment]
@robbyhorvath Could you rebase or merge master to your branch, there was another issue with CI which has been fixed and pushed to the main branch

**Comment by seeruyy** [comment]
@robbyhorvath Something is still going wrong, I'm working on that. sorry for the inconvenience.

**Review by seeruyy — APPROVED** [review]

**Pull request merged**
